# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Glad_config = debug
  ImGui_config = debug
  physicsEngine_config = debug

else ifeq ($(config),release)
  Glad_config = release
  ImGui_config = release
  physicsEngine_config = release

else ifeq ($(config),dist)
  Glad_config = dist
  ImGui_config = dist
  physicsEngine_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Glad ImGui physicsEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C physicsEngine/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C physicsEngine/vendor/imgui -f Makefile config=$(ImGui_config)
endif

physicsEngine: Glad ImGui
ifneq (,$(physicsEngine_config))
	@echo "==== Building physicsEngine ($(physicsEngine_config)) ===="
	@${MAKE} --no-print-directory -C physicsEngine -f Makefile config=$(physicsEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C physicsEngine/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C physicsEngine/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C physicsEngine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   physicsEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"